// Flat C exports observed in RMCLIENT.dll. Unknown ABIs are intentionally not declared.
// Validated dialects: ISO C17/C23/C26 draft and Windissect C20 (C ABI under C++20).
#pragma once
#ifndef RMCLIENT_C_H
#define RMCLIENT_C_H
#if defined(__cplusplus)
#  if __cplusplus < 202002L
#    define WINDISSECT_C20_PROFILE 0
#  else
#    define WINDISSECT_C20_PROFILE 1
#  endif
extern "C" {
#else
#  if defined(__STDC_VERSION__) && __STDC_VERSION__ < 201710L
#    error "Windissect C output requires C17 or newer"
#  endif
#  define WINDISSECT_C20_PROFILE 0
#  define WINDISSECT_C_STANDARD __STDC_VERSION__
#endif

// Export: HamCompleteActivityRestore (ABI unverified)
// Export: HamGetInterruptiveUIStateForAumid (ABI unverified)
// Export: HamHostIdFind (ABI unverified)
// Export: RmGameModeRegisterProcess (ABI unverified)
// Export: HamConnectForStateChangeNotifications (ABI unverified)
// Export: HamConnectForServicing (ABI unverified)
// Export: HamConnectForExtendedExecution (ABI unverified)
// Export: HamDisconnectFromServer (ABI unverified)
// Export: HamConnectForSessionState (ABI unverified)
// Export: HamConnectForDebugging (ABI unverified)
// Export: RmGameModeGetLargestValidResourceRequest (ABI unverified)
// Export: HamHostIdRetrieveDynamicId (ABI unverified)
// Export: CrmRegister (ABI unverified)
// Export: CrmUnregister (ABI unverified)
// Export: CrmActivityAllocate (ABI unverified)
// Export: CempHeapFree (ABI unverified)
// Export: CrmActivityFreeWindowClosedReasons (ABI unverified)
// Export: DestroyActivityCoordinatorPolicy (ABI unverified)
// Export: HamFreeBuffer (ABI unverified)
// Export: HampConnectionObjectDestroy (ABI unverified)
// Export: MIDL_user_free (ABI unverified)
// Export: CrmActivityFree (ABI unverified)
// Export: HamHostIdInitializeKey (ABI unverified)
// Export: HamCreateActivityForProcess (ABI unverified)
// Export: HamCreateActivity (ABI unverified)
// Export: HamCreateActivityEx (ABI unverified)
// Export: HamPopulateActivityPropertiesByClass (ABI unverified)
// Export: HamCloseActivity (ABI unverified)
// Export: HamPopulateActivityProperties (ABI unverified)
// Export: HamHostIdFindOrCreate (ABI unverified)
// Export: HamQueryPackageUsageInfo (ABI unverified)
// Export: DllGetActivationFactory (ABI unverified)
// Export: HamCreateExtendedExecution (ABI unverified)
// Export: HamGetApplicationInterruptiveUIState (ABI unverified)
// Export: HamQueryCallerTerminateReason (ABI unverified)
// Export: HamGetStateSnapshotForAumid (ABI unverified)
// Export: HamRegisterDesktopProcessWithAppContainerToken (ABI unverified)
// Export: HamUpdateActivityProperties (ABI unverified)
// Export: DllCanUnloadNow (ABI unverified)
// Export: HamStartActivityAsync (ABI unverified)
// Export: RmAccessCheck (ABI unverified)
// Export: AppModelQueryLifecyclePolicy (ABI unverified)
// Export: HamGetApplicationStateForPsmKey (ABI unverified)
// Export: HamHostIdCreateSingleUse (ABI unverified)
// Export: RmGetNotification (ABI unverified)
// Export: RmAcquireResources (ABI unverified)
// Export: RmReleaseResources (ABI unverified)
// Export: CrmActivityStop (ABI unverified)
// Export: HamTerminateActivityHost (ABI unverified)
// Export: HamTerminateActivityHostEx (ABI unverified)
// Export: CrmActivityStart (ABI unverified)
// Export: HamStopActivity (ABI unverified)
// Export: HamServicingOpenPackageHandle (ABI unverified)
// Export: HamInitializeActivityAutoRestartProperties (ABI unverified)
// Export: HamInitializeStateChangeFlags (ABI unverified)
// Export: RmActivityImportanceInitialize (ABI unverified)
// Export: HamDebugOpenPackageHandle (ABI unverified)
// Export: HamServicingQueryActiveAppsInPackage (ABI unverified)
// Export: HamTryEstimateRemainingQuiesceTime (ABI unverified)
// Export: HamTerminateApplicationHost (ABI unverified)
// Export: HamServicingClosePackageHandle (ABI unverified)
// Export: HamInitializeActivityDynamicProperties (ABI unverified)
// Export: HamPlmNotifyNewSession (ABI unverified)
// Export: HamConnectToServer (ABI unverified)
// Export: HamConnectToServerEx (ABI unverified)
// Export: CrmActivityQueryWindowClosedReasons (ABI unverified)
// Export: HamDebugClosePackageHandle (ABI unverified)
// Export: HamDebugQueryPackageState (ABI unverified)
// Export: RmEnableLimits (ABI unverified)
// Export: HamStartExtendedExecutionAsync (ABI unverified)
// Export: HamCompleteExtendedExecution (ABI unverified)
// Export: HamTerminateSelfEx (ABI unverified)
// Export: HamIsHostBeingDebugged (ABI unverified)
// Export: CrmActivityRenew (ABI unverified)
// Export: CrmWorkStart (ABI unverified)
// Export: CrmWorkStop (ABI unverified)
// Export: _guard_check_icall_nop (ABI unverified)
// Export: wil_StagingConfig_LogFeatureProcessUsage (ABI unverified)
// Export: HamServicingEnableServicing (ABI unverified)
// Export: CrmActivityRequest (ABI unverified)
// Export: CrmActivityWindowClosedReasonUnsubscribe (ABI unverified)
// Export: HamSessionStateLogoffSession (ABI unverified)
// Export: HamQueryPackageStateSummary (ABI unverified)
// Export: RmGameModeInitializeResourceRequest (ABI unverified)
// Export: CrmActivityWindowClosedReasonSubscribe (ABI unverified)
// Export: HamDisconnectForDebugging (ABI unverified)
// Export: HamDisconnectForExtendedExecution (ABI unverified)
// Export: HamDisconnectForFullTrust (ABI unverified)
// Export: HamDisconnectForServicing (ABI unverified)
// Export: HamDisconnectForSessionState (ABI unverified)
// Export: HamDisconnectForStateChangeNotifications (ABI unverified)
// Export: CrmSubscribe (ABI unverified)
// Export: CrmUnsubscribe (ABI unverified)
// Export: RmAcquireResourceSet (ABI unverified)
// Export: RmAcquireResourceSetEx (ABI unverified)
// Export: RmApplyResourceSet (ABI unverified)
// Export: RmApplyResourceSetToHost (ABI unverified)
// Export: RmConnectToResourceManager (ABI unverified)
// Export: RmDisconnectFromResourceManager (ABI unverified)
// Export: RmQueryHostMemoryLimitValues (ABI unverified)
// Export: RmRegisterActivityHostCallbacks (ABI unverified)
// Export: RmReleaseResourceSet (ABI unverified)
// Export: RmReleaseResourceSetEx (ABI unverified)
// Export: RmSetHostLimit (ABI unverified)
// Export: RmUnregisterActivityHost (ABI unverified)
// Export: RmUnregisterActivityHostCallbacks (ABI unverified)
// Export: RmUpdateResourceSetProperties (ABI unverified)
// Export: DllGetClassObject (ABI unverified)
// Export: RmGameModeDisableForRegisteredProcess (ABI unverified)
// Export: RmGameModeDisableForRegisteredProcessById (ABI unverified)
// Export: RmGameModeReenableForRegisteredProcess (ABI unverified)
// Export: RmGameModeReenableForRegisteredProcessById (ABI unverified)
// Export: RmGameModeRegisterPairedAuxiliaryProcess (ABI unverified)
// Export: RmGameModeRegisterPairedAuxiliaryProcessById (ABI unverified)
// Export: RmGameModeRegisterProcessById (ABI unverified)
// Export: RmGameModeUnregisterProcess (ABI unverified)
// Export: RmGameModeUnregisterProcessById (ABI unverified)
// Export: RmRegisterForGameMode (ABI unverified)
// Export: RmUnregisterForGameMode (ABI unverified)
// Export: RmActivityImportanceTakeMostImportant (ABI unverified)
// Export: RmResourceLimitFlagsInitialize (ABI unverified)
// Export: RmResourceLimitsInitialize (ABI unverified)
// Export: RmResourceSetPropertiesInitialize (ABI unverified)
// Export: RmAccessCheckOnSelf (ABI unverified)
// Export: RmAvailabilityCheck (ABI unverified)
// Export: RmRegisterResource (ABI unverified)
// Export: HamAddDependency (ABI unverified)
// Export: HamAddHostDependency (ABI unverified)
// Export: HamAssociateActivityContext (ABI unverified)
// Export: HamConnectForFullTrust (ABI unverified)
// Export: HamDebugModeEnable (ABI unverified)
// Export: HamDebugSuspendPackage (ABI unverified)
// Export: HamDebugTerminatePackage (ABI unverified)
// Export: HamFullTrustClosePackageHandle (ABI unverified)
// Export: HamFullTrustOpenPackageHandle (ABI unverified)
// Export: HamFullTrustTerminatePackage (ABI unverified)
// Export: HamGetPackageInterruptiveUIState (ABI unverified)
// Export: HamPendDiagnosticsToWaitTimeout (ABI unverified)
// Export: HamQueryActivityPendDiagnostics (ABI unverified)
// Export: HamQueryApplicationUsageInfo (ABI unverified)
// Export: HamQueryHostStateSummary (ABI unverified)
// Export: HamQueryTaskCompletionsForTerminateGraph (ABI unverified)
// Export: HamRemoveDependency (ABI unverified)
// Export: HamRemoveHostDependency (ABI unverified)
// Export: HamResetExternalResourcePriority (ABI unverified)
// Export: HamServicingQueryPackageState (ABI unverified)
// Export: HamServicingTerminatePackage (ABI unverified)
// Export: HamSessionStateLogoffUser (ABI unverified)
// Export: HamSetCommitProperties (ABI unverified)
// Export: HamSetExternalResourcePriority (ABI unverified)
// Export: HamTerminateHostOnProcessExit (ABI unverified)
// Export: HamTerminateIfSuspendedByProcess (ABI unverified)
// Export: HamTerminateSelf (ABI unverified)
// Export: HamTerminateSelfOnProcessExit (ABI unverified)
// Export: CrmActivityRequestAndWait (ABI unverified)
// Export: CreateActivityCoordinatorPolicy (ABI unverified)
// Export: GetActivityCoordinatorPolicyResourceCondition (ABI unverified)
// Export: IsActivityCoordinatorResourceSupported (ABI unverified)
// Export: SetActivityCoordinatorPolicyResourceCondition (ABI unverified)
// Export: SubscribeActivityCoordinatorPolicy (ABI unverified)
// Export: UnsubscribeActivityCoordinatorPolicy (ABI unverified)
// Export: HamCreateAutoRestartActivity (ABI unverified)

#ifdef __cplusplus
} // extern "C"
#endif
#endif // RMCLIENT_C_H
